// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module process_data_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_32u_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_elem_0_0_0_0_0_val,
        layer3_out_din,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap,
        layer3_out_full_n,
        layer3_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] in_elem_0_0_0_0_0_val;
output  [511:0] layer3_out_din;
input  [16:0] layer3_out_num_data_valid;
input  [16:0] layer3_out_fifo_cap;
input   layer3_out_full_n;
output   layer3_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer3_out_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
reg    layer3_out_blk_n;
wire    ap_CS_fsm_state4;
reg   [0:0] icmp_ln289_reg_479;
reg   [0:0] and_ln289_3_reg_493;
wire   [0:0] icmp_ln289_fu_158_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln289_3_fu_215_p2;
reg   [15:0] res_out_reg_497;
wire    ap_CS_fsm_state3;
reg   [15:0] res_out_152_reg_502;
reg   [15:0] res_out_153_reg_507;
reg   [15:0] res_out_154_reg_512;
reg   [15:0] res_out_4_reg_517;
reg   [15:0] res_out_5_reg_522;
reg   [15:0] res_out_6_reg_527;
reg   [15:0] res_out_7_reg_532;
reg   [15:0] res_out_8_reg_537;
reg   [15:0] res_out_9_reg_542;
reg   [15:0] res_out_130_reg_547;
reg   [15:0] res_out_131_reg_552;
reg   [15:0] res_out_132_reg_557;
reg   [15:0] res_out_133_reg_562;
reg   [15:0] res_out_134_reg_567;
reg   [15:0] res_out_135_reg_572;
reg   [15:0] res_out_136_reg_577;
reg   [15:0] res_out_137_reg_582;
reg   [15:0] res_out_138_reg_587;
reg   [15:0] res_out_139_reg_592;
reg   [15:0] res_out_140_reg_597;
reg   [15:0] res_out_141_reg_602;
reg   [15:0] res_out_142_reg_607;
reg   [15:0] res_out_143_reg_612;
reg   [15:0] res_out_144_reg_617;
reg   [15:0] res_out_145_reg_622;
reg   [15:0] res_out_146_reg_627;
reg   [15:0] res_out_147_reg_632;
reg   [15:0] res_out_148_reg_637;
reg   [15:0] res_out_149_reg_642;
reg   [15:0] res_out_150_reg_647;
reg   [15:0] res_out_151_reg_652;
reg    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_start;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_done;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_idle;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_ready;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31_ap_vld;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_done;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_idle;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_ready;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_0;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_1;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_2;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_3;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_4;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_5;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_6;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_7;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_8;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_9;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_10;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_11;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_12;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_13;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_14;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_15;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_16;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_17;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_18;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_19;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_20;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_21;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_22;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_23;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_24;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_25;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_26;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_27;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_28;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_29;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_30;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_31;
wire   [31:0] select_ln323_fu_455_p3;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_88_p4;
reg    ap_predicate_op57_write_state4;
reg    ap_block_state4;
wire   [0:0] icmp_ln313_fu_391_p2;
wire   [0:0] icmp_ln317_fu_438_p2;
reg    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg;
wire   [31:0] select_ln328_fu_408_p3;
wire   [31:0] add_ln317_fu_433_p2;
wire   [31:0] add_ln313_fu_386_p2;
wire   [30:0] tmp_260_fu_177_p4;
wire   [30:0] tmp_261_fu_193_p4;
wire   [0:0] icmp_ln289_8_fu_187_p2;
wire   [0:0] icmp_ln289_9_fu_203_p2;
wire   [0:0] and_ln289_fu_209_p2;
wire   [0:0] grp_fu_149_p2;
wire   [31:0] add_ln328_fu_403_p2;
wire   [31:0] add_ln323_fu_450_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_condition_223;
reg    ap_condition_307;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31 = 16'd0;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg = 1'b0;
end

process_data_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_start),
    .ap_done(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_done),
    .ap_idle(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_idle),
    .ap_ready(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31_ap_vld)
);

process_data_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start),
    .ap_done(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_done),
    .ap_idle(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_idle),
    .ap_ready(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38),
    .ap_return_0(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_0),
    .ap_return_1(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_1),
    .ap_return_2(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_2),
    .ap_return_3(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_3),
    .ap_return_4(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_4),
    .ap_return_5(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_5),
    .ap_return_6(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_6),
    .ap_return_7(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_7),
    .ap_return_8(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_8),
    .ap_return_9(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_9),
    .ap_return_10(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_10),
    .ap_return_11(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_11),
    .ap_return_12(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_12),
    .ap_return_13(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_13),
    .ap_return_14(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_14),
    .ap_return_15(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_15),
    .ap_return_16(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_16),
    .ap_return_17(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_17),
    .ap_return_18(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_18),
    .ap_return_19(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_19),
    .ap_return_20(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_20),
    .ap_return_21(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_21),
    .ap_return_22(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_22),
    .ap_return_23(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_23),
    .ap_return_24(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_24),
    .ap_return_25(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_25),
    .ap_return_26(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_26),
    .ap_return_27(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_27),
    .ap_return_28(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_28),
    .ap_return_29(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_29),
    .ap_return_30(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_30),
    .ap_return_31(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_31)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln289_fu_158_p2 == 1'd1) & (1'd1 == and_ln289_3_fu_215_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_ready == 1'b1)) begin
            grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((icmp_ln313_fu_391_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln313_fu_391_p2 == 1'd0)) begin
            pX_2 <= add_ln313_fu_386_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_307)) begin
        if ((icmp_ln317_fu_438_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln317_fu_438_p2 == 1'd0)) begin
            pY_2 <= add_ln317_fu_433_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_223)) begin
        if ((icmp_ln313_fu_391_p2 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln313_fu_391_p2 == 1'd0)) begin
            sX_2 <= select_ln328_fu_408_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln289_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln289_3_reg_493 <= and_ln289_3_fu_215_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln289_reg_479 <= icmp_ln289_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        res_out_130_reg_547 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_10;
        res_out_131_reg_552 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_11;
        res_out_132_reg_557 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_12;
        res_out_133_reg_562 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_13;
        res_out_134_reg_567 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_14;
        res_out_135_reg_572 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_15;
        res_out_136_reg_577 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_16;
        res_out_137_reg_582 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_17;
        res_out_138_reg_587 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_18;
        res_out_139_reg_592 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_19;
        res_out_140_reg_597 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_20;
        res_out_141_reg_602 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_21;
        res_out_142_reg_607 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_22;
        res_out_143_reg_612 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_23;
        res_out_144_reg_617 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_24;
        res_out_145_reg_622 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_25;
        res_out_146_reg_627 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_26;
        res_out_147_reg_632 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_27;
        res_out_148_reg_637 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_28;
        res_out_149_reg_642 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_29;
        res_out_150_reg_647 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_30;
        res_out_151_reg_652 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_31;
        res_out_152_reg_502 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_1;
        res_out_153_reg_507 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_2;
        res_out_154_reg_512 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_3;
        res_out_4_reg_517 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_4;
        res_out_5_reg_522 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_5;
        res_out_6_reg_527 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_6;
        res_out_7_reg_532 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_7;
        res_out_8_reg_537 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_8;
        res_out_9_reg_542 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_9;
        res_out_reg_497 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (icmp_ln313_fu_391_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        sY_2 <= ap_phi_mux_storemerge_phi_fu_88_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_30_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_31;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_32_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_33_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_34;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_35_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_36_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_37;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_38_o;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_391_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((icmp_ln317_fu_438_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = 32'd0;
        end else if ((icmp_ln317_fu_438_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = select_ln323_fu_455_p3;
        end else begin
            ap_phi_mux_storemerge_phi_fu_88_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_88_p4 = 'bx;
    end
end

always @ (*) begin
    if ((~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_start = 1'b1;
    end else begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config3_s_fu_95_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln289_3_reg_493) & (icmp_ln289_reg_479 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer3_out_blk_n = layer3_out_full_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (ap_predicate_op57_write_state4 == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer3_out_write = 1'b1;
    end else begin
        layer3_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln289_fu_158_p2 == 1'd1) & (1'd1 == and_ln289_3_fu_215_p2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln313_fu_386_p2 = (pX_2 + 32'd1);

assign add_ln317_fu_433_p2 = (pY_2 + 32'd1);

assign add_ln323_fu_450_p2 = (sY_2 + 32'd1);

assign add_ln328_fu_403_p2 = (sX_2 + 32'd1);

assign and_ln289_3_fu_215_p2 = (grp_fu_149_p2 & and_ln289_fu_209_p2);

assign and_ln289_fu_209_p2 = (icmp_ln289_9_fu_203_p2 & icmp_ln289_8_fu_187_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1));
end

always @ (*) begin
    ap_condition_223 = (~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4));
end

always @ (*) begin
    ap_condition_307 = (~((layer3_out_full_n == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) & (icmp_ln313_fu_391_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4));
end

always @ (*) begin
    ap_predicate_op57_write_state4 = ((1'd1 == and_ln289_3_reg_493) & (icmp_ln289_reg_479 == 1'd1));
end

assign grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start = grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config3_mult_s_fu_123_ap_start_reg;

assign grp_fu_149_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln289_8_fu_187_p2 = (($signed(tmp_260_fu_177_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_9_fu_203_p2 = (($signed(tmp_261_fu_193_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_158_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_391_p2 = ((add_ln313_fu_386_p2 == 32'd128) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_438_p2 = ((add_ln317_fu_433_p2 == 32'd512) ? 1'b1 : 1'b0);

assign layer3_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_out_151_reg_652}, {res_out_150_reg_647}}, {res_out_149_reg_642}}, {res_out_148_reg_637}}, {res_out_147_reg_632}}, {res_out_146_reg_627}}, {res_out_145_reg_622}}, {res_out_144_reg_617}}, {res_out_143_reg_612}}, {res_out_142_reg_607}}, {res_out_141_reg_602}}, {res_out_140_reg_597}}, {res_out_139_reg_592}}, {res_out_138_reg_587}}, {res_out_137_reg_582}}, {res_out_136_reg_577}}, {res_out_135_reg_572}}, {res_out_134_reg_567}}, {res_out_133_reg_562}}, {res_out_132_reg_557}}, {res_out_131_reg_552}}, {res_out_130_reg_547}}, {res_out_9_reg_542}}, {res_out_8_reg_537}}, {res_out_7_reg_532}}, {res_out_6_reg_527}}, {res_out_5_reg_522}}, {res_out_4_reg_517}}, {res_out_154_reg_512}}, {res_out_153_reg_507}}, {res_out_152_reg_502}}, {res_out_reg_497}};

assign select_ln323_fu_455_p3 = ((grp_fu_149_p2[0:0] == 1'b1) ? 32'd2 : add_ln323_fu_450_p2);

assign select_ln328_fu_408_p3 = ((icmp_ln289_reg_479[0:0] == 1'b1) ? 32'd2 : add_ln328_fu_403_p2);

assign tmp_260_fu_177_p4 = {{pY_2[31:1]}};

assign tmp_261_fu_193_p4 = {{pX_2[31:1]}};

endmodule //process_data_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_32u_config3_s
